baseURL = "http://ccnmtl.columbia.edu/projects/lanretamhugo/"
metaDataFormat = "yaml"
languageCode = "en-us"
title = "The Republic of Lanretam Ministry of Health"

[params]
    shortTitle = "Lanretam"
